# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'nuget restore solution'
  inputs:
    restoreSolution: '$(solution)'

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet build'
#  inputs:
#    command: 'build'
#    projects: '$(solution)'
#    arguments: '-c $(buildConfiguration)'

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet test'
#  inputs:
#    command: 'test'
#    projects: '$(Build.SourcesDirectory)/src/ExampleTestProject/ExampleTestProject.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.SourcesDirectory)/src/XFeatureTest/XFeatureTest.csproj'
    configuration: '$(BuildConfiguration)'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PackageVersion'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'nuget'
    publishLocation: 'Container'

- task: CmdLine@2
  displayName: 'dotnet nuget push nuget.org'
  inputs:
    script: 'dotnet nuget push $(Build.ArtifactStagingDirectory)/XFeatureTest.$(PackageVersion).symbols.nupkg -k $(ApiKey) -s https://api.nuget.org/v3/index.json'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

- task: CmdLine@2
  displayName: 'dotnet nuget push nuget.org symbols'
  inputs:
    script: 'dotnet nuget push $(Build.ArtifactStagingDirectory)/XFeatureTest.$(PackageVersion).symbols.snupkg -k $(ApiKey) -s https://api.nuget.org/v3/index.json'
