# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**\*.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**\*ExampleTestProject.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/XFeatureTest.csproj'
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: 'byEnvVar'
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Public Nuget Feed'
